/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as SetupRouteImport } from './app/setup'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as IndexRouteImport } from './app/index'
import { Route as ApiSetupRouteImport } from './app/api.setup'
import { Route as ProtectedDashboardRouteImport } from './app/_protected.dashboard'
import { Route as ProtectedAdminRouteImport } from './app/_protected.admin'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './app/[.]well-known.openid-configuration'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './app/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './app/[.]well-known.oauth-authorization-server'
import { Route as ProtectedAdminIndexRouteImport } from './app/_protected.admin.index'
import { Route as ApiAuthSessionCheckRouteImport } from './app/api.auth.session-check'
import { Route as ApiAuthSplatRouteImport } from './app/api.auth.$'
import { Route as ProtectedAdminSettingsRouteImport } from './app/_protected.admin.settings'
import { Route as ProtectedAdminOauthClientsRouteImport } from './app/_protected.admin.oauth-clients'
import { Route as DotwellKnownOauthProtectedResourceApiMcpRouteImport } from './app/[.]well-known.oauth-protected-resource.api.mcp'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ApiAuthSessionCheckRoute = ApiAuthSessionCheckRouteImport.update({
  id: '/api/auth/session-check',
  path: '/api/auth/session-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminOauthClientsRoute =
  ProtectedAdminOauthClientsRouteImport.update({
    id: '/oauth-clients',
    path: '/oauth-clients',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const DotwellKnownOauthProtectedResourceApiMcpRoute =
  DotwellKnownOauthProtectedResourceApiMcpRouteImport.update({
    id: '/api/mcp',
    path: '/api/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/setup': typeof ApiSetupRoute
  '/admin/oauth-clients': typeof ProtectedAdminOauthClientsRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session-check': typeof ApiAuthSessionCheckRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/setup': typeof ApiSetupRoute
  '/admin/oauth-clients': typeof ProtectedAdminOauthClientsRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session-check': typeof ApiAuthSessionCheckRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/setup': typeof ApiSetupRoute
  '/_protected/admin/oauth-clients': typeof ProtectedAdminOauthClientsRoute
  '/_protected/admin/settings': typeof ProtectedAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session-check': typeof ApiAuthSessionCheckRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/admin'
    | '/dashboard'
    | '/api/setup'
    | '/admin/oauth-clients'
    | '/admin/settings'
    | '/api/auth/$'
    | '/api/auth/session-check'
    | '/admin/'
    | '/.well-known/oauth-protected-resource/api/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/dashboard'
    | '/api/setup'
    | '/admin/oauth-clients'
    | '/admin/settings'
    | '/api/auth/$'
    | '/api/auth/session-check'
    | '/admin'
    | '/.well-known/oauth-protected-resource/api/mcp'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/setup'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/api/setup'
    | '/_protected/admin/oauth-clients'
    | '/_protected/admin/settings'
    | '/api/auth/$'
    | '/api/auth/session-check'
    | '/_protected/admin/'
    | '/.well-known/oauth-protected-resource/api/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSessionCheckRoute: typeof ApiAuthSessionCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/api/auth/session-check': {
      id: '/api/auth/session-check'
      path: '/api/auth/session-check'
      fullPath: '/api/auth/session-check'
      preLoaderRoute: typeof ApiAuthSessionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/settings': {
      id: '/_protected/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/oauth-clients': {
      id: '/_protected/admin/oauth-clients'
      path: '/oauth-clients'
      fullPath: '/admin/oauth-clients'
      preLoaderRoute: typeof ProtectedAdminOauthClientsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/.well-known/oauth-protected-resource/api/mcp': {
      id: '/.well-known/oauth-protected-resource/api/mcp'
      path: '/api/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminOauthClientsRoute: typeof ProtectedAdminOauthClientsRoute
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminOauthClientsRoute: ProtectedAdminOauthClientsRoute,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceApiMcpRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceApiMcpRoute:
      DotwellKnownOauthProtectedResourceApiMcpRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSessionCheckRoute: ApiAuthSessionCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
